AgeVerificationExample.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AgeVerificationExample.Web.Models;

namespace AgeVerificationExample.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AgeVerificationExample.Web/Controllers/LoginHistoryController.cs
using AgeVerificationExample.Web.Contracts.Models;
using AgeVerificationExample.Web.Contracts.Repositories;
using AgeVerificationExample.Web.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics.Contracts;
using System.Threading.Tasks;

namespace AgeVerificationExample.Web.Controllers
{
    /// <summary>
    /// Controller to view login history
    /// </summary>
    [Authorize]
    public class LoginHistoryController : Controller
    {
        private readonly ILoginAttemptRepository loginAttemptRepository;

        public LoginHistoryController(ILoginAttemptRepository loginAttemptRepository)
        {
            this.loginAttemptRepository = loginAttemptRepository;
        }

        /// <summary>
        /// List the first page of login attempts by the user
        /// </summary>
        /// <returns>The view containing the list</returns>
        public async Task<IActionResult> Index()
        {
            return await List(new LoginAttemptPagedList());
        }

        public async Task<IActionResult> List(LoginAttemptPagedList model)
        {
            Contract.Requires(model != null);

            // Always set the user parameters of the model on each page (so we don't need to store this sensitive data in the view)
            model.UserId = this.User.GetUserId();
            model = await this.loginAttemptRepository.GetUserLoginAttempts(model);
            return this.View(nameof(this.Index), model);
        }

        public async Task<IActionResult> Chart()
        {
            var model = await this.loginAttemptRepository.GetLoginStatusCountsForPeriodAsync(30);
            return this.View(model);
        }
    }
}

AgeVerificationExample.Web/Views/Home/Index.cshtml
@using AgeVerificationExample.Web.Contracts
@inject IApplicationUserContext UserContext
@{
    ViewData["Title"] = "Home Page";
}

    <div class="text-center">
        <h1 class="display-4">Welcome</h1>

        @if (!UserContext.IsSignedIn(User))
        {
            <p>
                Please <a asp-area="Identity" asp-page="/Account/Login">Login</a> or
                <a asp-area="Identity" asp-page="/Account/Register">Register</a>
            </p>
        }
        else
        {
            <p>
                Hello. You are logged in as <span class="text-dark">@User.Identity.Name</span>.
            </p>
            <p>
                Please <a asp-controller="LoginHistory" asp-action="Index">View your login history</a> or
                <a asp-controller="LoginHistory" asp-action="Chart">View the login history statistics</a>
            </p>
        }
    </div>